# Generated by Django 4.0.3 on 2022-04-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('photo', models.ImageField(blank=True, default='face_django_app/static/img/noimg.png', null=True, upload_to='face_django_app/facerec/detected/')),
            ],
        ),
        migrations.CreateModel(
            name='Detected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('photo', models.ImageField(default='face_django_app/facerec/detected/noimg.png', upload_to='face_django_app/facerec/detected')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.employee')),
            ],
        ),
    ]
